// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'api_model_rates.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Rates _$RatesFromJson(Map<String, dynamic> json) => Rates(
      AED: (json['AED'] as num).toDouble(),
      AFN: (json['AFN'] as num).toDouble(),
      ALL: (json['ALL'] as num).toDouble(),
      AMD: (json['AMD'] as num).toDouble(),
      ANG: (json['ANG'] as num).toDouble(),
      AOA: (json['AOA'] as num).toDouble(),
      ARS: (json['ARS'] as num).toDouble(),
      AUD: (json['AUD'] as num).toDouble(),
      AWG: (json['AWG'] as num).toDouble(),
      AZN: (json['AZN'] as num).toDouble(),
      BAM: (json['BAM'] as num).toDouble(),
      BBD: (json['BBD'] as num).toDouble(),
      BDT: (json['BDT'] as num).toDouble(),
      BGN: (json['BGN'] as num).toDouble(),
      BHD: (json['BHD'] as num).toDouble(),
      BIF: (json['BIF'] as num).toDouble(),
      BMD: (json['BMD'] as num).toDouble(),
      BND: (json['BND'] as num).toDouble(),
      BOB: (json['BOB'] as num).toDouble(),
      BRL: (json['BRL'] as num).toDouble(),
      BSD: (json['BSD'] as num).toDouble(),
      BTC: (json['BTC'] as num).toDouble(),
      BTN: (json['BTN'] as num).toDouble(),
      BWP: (json['BWP'] as num).toDouble(),
      BYN: (json['BYN'] as num).toDouble(),
      BYR: (json['BYR'] as num).toDouble(),
      BZD: (json['BZD'] as num).toDouble(),
      CAD: (json['CAD'] as num).toDouble(),
      CDF: (json['CDF'] as num).toDouble(),
      CHF: (json['CHF'] as num).toDouble(),
      CLF: (json['CLF'] as num).toDouble(),
      CLP: (json['CLP'] as num).toDouble(),
      CNY: (json['CNY'] as num).toDouble(),
      COP: (json['COP'] as num).toDouble(),
      CRC: (json['CRC'] as num).toDouble(),
      CUC: (json['CUC'] as num).toDouble(),
      CUP: (json['CUP'] as num).toDouble(),
      CVE: (json['CVE'] as num).toDouble(),
      CZK: (json['CZK'] as num).toDouble(),
      DJF: (json['DJF'] as num).toDouble(),
      DKK: (json['DKK'] as num).toDouble(),
      DOP: (json['DOP'] as num).toDouble(),
      DZD: (json['DZD'] as num).toDouble(),
      EGP: (json['EGP'] as num).toDouble(),
      ERN: (json['ERN'] as num).toDouble(),
      ETB: (json['ETB'] as num).toDouble(),
      EUR: json['EUR'] as int,
      FJD: (json['FJD'] as num).toDouble(),
      FKP: (json['FKP'] as num).toDouble(),
      GBP: (json['GBP'] as num).toDouble(),
      GEL: (json['GEL'] as num).toDouble(),
      GGP: (json['GGP'] as num).toDouble(),
      GHS: (json['GHS'] as num).toDouble(),
      GIP: (json['GIP'] as num).toDouble(),
      GMD: (json['GMD'] as num).toDouble(),
      GNF: (json['GNF'] as num).toDouble(),
      GTQ: (json['GTQ'] as num).toDouble(),
      GYD: (json['GYD'] as num).toDouble(),
      HKD: (json['HKD'] as num).toDouble(),
      HNL: (json['HNL'] as num).toDouble(),
      HRK: (json['HRK'] as num).toDouble(),
      HTG: (json['HTG'] as num).toDouble(),
      HUF: (json['HUF'] as num).toDouble(),
      IDR: (json['IDR'] as num).toDouble(),
      ILS: (json['ILS'] as num).toDouble(),
      IMP: (json['IMP'] as num).toDouble(),
      INR: (json['INR'] as num).toDouble(),
      IQD: (json['IQD'] as num).toDouble(),
      IRR: (json['IRR'] as num).toDouble(),
      ISK: (json['ISK'] as num).toDouble(),
      JEP: (json['JEP'] as num).toDouble(),
      JMD: (json['JMD'] as num).toDouble(),
      JOD: (json['JOD'] as num).toDouble(),
      JPY: (json['JPY'] as num).toDouble(),
      KES: (json['KES'] as num).toDouble(),
      KGS: (json['KGS'] as num).toDouble(),
      KHR: (json['KHR'] as num).toDouble(),
      KMF: (json['KMF'] as num).toDouble(),
      KPW: (json['KPW'] as num).toDouble(),
      KRW: (json['KRW'] as num).toDouble(),
      KWD: (json['KWD'] as num).toDouble(),
      KYD: (json['KYD'] as num).toDouble(),
      KZT: (json['KZT'] as num).toDouble(),
      LAK: (json['LAK'] as num).toDouble(),
      LBP: (json['LBP'] as num).toDouble(),
      LKR: (json['LKR'] as num).toDouble(),
      LRD: (json['LRD'] as num).toDouble(),
      LSL: (json['LSL'] as num).toDouble(),
      LTL: (json['LTL'] as num).toDouble(),
      LVL: (json['LVL'] as num).toDouble(),
      LYD: (json['LYD'] as num).toDouble(),
      MAD: (json['MAD'] as num).toDouble(),
      MDL: (json['MDL'] as num).toDouble(),
      MGA: (json['MGA'] as num).toDouble(),
      MKD: (json['MKD'] as num).toDouble(),
      MMK: (json['MMK'] as num).toDouble(),
      MNT: (json['MNT'] as num).toDouble(),
      MOP: (json['MOP'] as num).toDouble(),
      MRO: (json['MRO'] as num).toDouble(),
      MUR: (json['MUR'] as num).toDouble(),
      MVR: (json['MVR'] as num).toDouble(),
      MWK: (json['MWK'] as num).toDouble(),
      MXN: (json['MXN'] as num).toDouble(),
      MYR: (json['MYR'] as num).toDouble(),
      MZN: (json['MZN'] as num).toDouble(),
      NAD: (json['NAD'] as num).toDouble(),
      NGN: (json['NGN'] as num).toDouble(),
      NIO: (json['NIO'] as num).toDouble(),
      NOK: (json['NOK'] as num).toDouble(),
      NPR: (json['NPR'] as num).toDouble(),
      NZD: (json['NZD'] as num).toDouble(),
      OMR: (json['OMR'] as num).toDouble(),
      PAB: (json['PAB'] as num).toDouble(),
      PEN: (json['PEN'] as num).toDouble(),
      PGK: (json['PGK'] as num).toDouble(),
      PHP: (json['PHP'] as num).toDouble(),
      PKR: (json['PKR'] as num).toDouble(),
      PLN: (json['PLN'] as num).toDouble(),
      PYG: (json['PYG'] as num).toDouble(),
      QAR: (json['QAR'] as num).toDouble(),
      RON: (json['RON'] as num).toDouble(),
      RSD: (json['RSD'] as num).toDouble(),
      RUB: (json['RUB'] as num).toDouble(),
      RWF: (json['RWF'] as num).toDouble(),
      SAR: (json['SAR'] as num).toDouble(),
      SBD: (json['SBD'] as num).toDouble(),
      SCR: (json['SCR'] as num).toDouble(),
      SDG: (json['SDG'] as num).toDouble(),
      SEK: (json['SEK'] as num).toDouble(),
      SGD: (json['SGD'] as num).toDouble(),
      SHP: (json['SHP'] as num).toDouble(),
      SLL: (json['SLL'] as num).toDouble(),
      SOS: (json['SOS'] as num).toDouble(),
      SRD: (json['SRD'] as num).toDouble(),
      STD: (json['STD'] as num).toDouble(),
      SVC: (json['SVC'] as num).toDouble(),
      SYP: (json['SYP'] as num).toDouble(),
      SZL: (json['SZL'] as num).toDouble(),
      THB: (json['THB'] as num).toDouble(),
      TJS: (json['TJS'] as num).toDouble(),
      TMT: (json['TMT'] as num).toDouble(),
      TND: (json['TND'] as num).toDouble(),
      TOP: (json['TOP'] as num).toDouble(),
      TRY: (json['TRY'] as num).toDouble(),
      TTD: (json['TTD'] as num).toDouble(),
      TWD: (json['TWD'] as num).toDouble(),
      TZS: (json['TZS'] as num).toDouble(),
      UAH: (json['UAH'] as num).toDouble(),
      UGX: (json['UGX'] as num).toDouble(),
      USD: (json['USD'] as num).toDouble(),
      UYU: (json['UYU'] as num).toDouble(),
      UZS: (json['UZS'] as num).toDouble(),
      VEF: (json['VEF'] as num).toDouble(),
      VND: (json['VND'] as num).toDouble(),
      VUV: (json['VUV'] as num).toDouble(),
      WST: (json['WST'] as num).toDouble(),
      XAF: (json['XAF'] as num).toDouble(),
      XAG: (json['XAG'] as num).toDouble(),
      XAU: (json['XAU'] as num).toDouble(),
      XCD: (json['XCD'] as num).toDouble(),
      XDR: (json['XDR'] as num).toDouble(),
      XOF: (json['XOF'] as num).toDouble(),
      XPF: (json['XPF'] as num).toDouble(),
      YER: (json['YER'] as num).toDouble(),
      ZAR: (json['ZAR'] as num).toDouble(),
      ZMK: (json['ZMK'] as num).toDouble(),
      ZMW: (json['ZMW'] as num).toDouble(),
      ZWL: (json['ZWL'] as num).toDouble(),
    );

Map<String, dynamic> _$RatesToJson(Rates instance) => <String, dynamic>{
      'AED': instance.AED,
      'AFN': instance.AFN,
      'ALL': instance.ALL,
      'AMD': instance.AMD,
      'ANG': instance.ANG,
      'AOA': instance.AOA,
      'ARS': instance.ARS,
      'AUD': instance.AUD,
      'AWG': instance.AWG,
      'AZN': instance.AZN,
      'BAM': instance.BAM,
      'BBD': instance.BBD,
      'BDT': instance.BDT,
      'BGN': instance.BGN,
      'BHD': instance.BHD,
      'BIF': instance.BIF,
      'BMD': instance.BMD,
      'BND': instance.BND,
      'BOB': instance.BOB,
      'BRL': instance.BRL,
      'BSD': instance.BSD,
      'BTC': instance.BTC,
      'BTN': instance.BTN,
      'BWP': instance.BWP,
      'BYN': instance.BYN,
      'BYR': instance.BYR,
      'BZD': instance.BZD,
      'CAD': instance.CAD,
      'CDF': instance.CDF,
      'CHF': instance.CHF,
      'CLF': instance.CLF,
      'CLP': instance.CLP,
      'CNY': instance.CNY,
      'COP': instance.COP,
      'CRC': instance.CRC,
      'CUC': instance.CUC,
      'CUP': instance.CUP,
      'CVE': instance.CVE,
      'CZK': instance.CZK,
      'DJF': instance.DJF,
      'DKK': instance.DKK,
      'DOP': instance.DOP,
      'DZD': instance.DZD,
      'EGP': instance.EGP,
      'ERN': instance.ERN,
      'ETB': instance.ETB,
      'EUR': instance.EUR,
      'FJD': instance.FJD,
      'FKP': instance.FKP,
      'GBP': instance.GBP,
      'GEL': instance.GEL,
      'GGP': instance.GGP,
      'GHS': instance.GHS,
      'GIP': instance.GIP,
      'GMD': instance.GMD,
      'GNF': instance.GNF,
      'GTQ': instance.GTQ,
      'GYD': instance.GYD,
      'HKD': instance.HKD,
      'HNL': instance.HNL,
      'HRK': instance.HRK,
      'HTG': instance.HTG,
      'HUF': instance.HUF,
      'IDR': instance.IDR,
      'ILS': instance.ILS,
      'IMP': instance.IMP,
      'INR': instance.INR,
      'IQD': instance.IQD,
      'IRR': instance.IRR,
      'ISK': instance.ISK,
      'JEP': instance.JEP,
      'JMD': instance.JMD,
      'JOD': instance.JOD,
      'JPY': instance.JPY,
      'KES': instance.KES,
      'KGS': instance.KGS,
      'KHR': instance.KHR,
      'KMF': instance.KMF,
      'KPW': instance.KPW,
      'KRW': instance.KRW,
      'KWD': instance.KWD,
      'KYD': instance.KYD,
      'KZT': instance.KZT,
      'LAK': instance.LAK,
      'LBP': instance.LBP,
      'LKR': instance.LKR,
      'LRD': instance.LRD,
      'LSL': instance.LSL,
      'LTL': instance.LTL,
      'LVL': instance.LVL,
      'LYD': instance.LYD,
      'MAD': instance.MAD,
      'MDL': instance.MDL,
      'MGA': instance.MGA,
      'MKD': instance.MKD,
      'MMK': instance.MMK,
      'MNT': instance.MNT,
      'MOP': instance.MOP,
      'MRO': instance.MRO,
      'MUR': instance.MUR,
      'MVR': instance.MVR,
      'MWK': instance.MWK,
      'MXN': instance.MXN,
      'MYR': instance.MYR,
      'MZN': instance.MZN,
      'NAD': instance.NAD,
      'NGN': instance.NGN,
      'NIO': instance.NIO,
      'NOK': instance.NOK,
      'NPR': instance.NPR,
      'NZD': instance.NZD,
      'OMR': instance.OMR,
      'PAB': instance.PAB,
      'PEN': instance.PEN,
      'PGK': instance.PGK,
      'PHP': instance.PHP,
      'PKR': instance.PKR,
      'PLN': instance.PLN,
      'PYG': instance.PYG,
      'QAR': instance.QAR,
      'RON': instance.RON,
      'RSD': instance.RSD,
      'RUB': instance.RUB,
      'RWF': instance.RWF,
      'SAR': instance.SAR,
      'SBD': instance.SBD,
      'SCR': instance.SCR,
      'SDG': instance.SDG,
      'SEK': instance.SEK,
      'SGD': instance.SGD,
      'SHP': instance.SHP,
      'SLL': instance.SLL,
      'SOS': instance.SOS,
      'SRD': instance.SRD,
      'STD': instance.STD,
      'SVC': instance.SVC,
      'SYP': instance.SYP,
      'SZL': instance.SZL,
      'THB': instance.THB,
      'TJS': instance.TJS,
      'TMT': instance.TMT,
      'TND': instance.TND,
      'TOP': instance.TOP,
      'TRY': instance.TRY,
      'TTD': instance.TTD,
      'TWD': instance.TWD,
      'TZS': instance.TZS,
      'UAH': instance.UAH,
      'UGX': instance.UGX,
      'USD': instance.USD,
      'UYU': instance.UYU,
      'UZS': instance.UZS,
      'VEF': instance.VEF,
      'VND': instance.VND,
      'VUV': instance.VUV,
      'WST': instance.WST,
      'XAF': instance.XAF,
      'XAG': instance.XAG,
      'XAU': instance.XAU,
      'XCD': instance.XCD,
      'XDR': instance.XDR,
      'XOF': instance.XOF,
      'XPF': instance.XPF,
      'YER': instance.YER,
      'ZAR': instance.ZAR,
      'ZMK': instance.ZMK,
      'ZMW': instance.ZMW,
      'ZWL': instance.ZWL,
    };
